"""Build the complete Senate ranking from the same snapshot used on profiles."""
import json,html
from fractions import Fraction
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def build():
 records=[r for r in json.loads((ROOT/'data/incumbent_records_2026.json').read_text())['records'] if r['chamber']=='senate']
 assert len(records)==38 and len({r['district_number'] for r in records})==38
 roster=json.loads((ROOT/'data/whos_running_2026.json').read_text())['chambers']['senate'];parties={c['candidate_id']:c['party'] for d in roster.values() for c in d['candidates']}
 keys=['prime_sponsored','passed_chamber','became_law'];totals=[sum(r['legislation'][k] for r in records) for k in keys]
 score=lambda r:Fraction(38,3)*sum(Fraction(r['legislation'][k],t) for k,t in zip(keys,totals))
 assert sum(score(r) for r in records)==38
 rows=[]
 for r in sorted(records,key=lambda r:(-score(r),r['candidate_name'])):
  s=score(r);party=parties[r['candidate_id']];peers=[p for p in records if parties[p['candidate_id']]==party];rank=1+sum(score(p)>s for p in records);prank=1+sum(score(p)>s for p in peers)
  slug=r['candidate_id'].split('-primary-',1)[1];name=html.escape(r['candidate_name']);name=f'<a href="{slug}.html#riep-legislative-index">{name}</a>' if (ROOT/'candidates'/f'{slug}.html').exists() else name
  rows.append(f'<tr id="district-{r["district_number"]}" data-name="{html.escape(r["candidate_name"].lower(),quote=True)}"><td>{rank}</td><th scope="row">{name}</th><td>{r["district_number"]}</td><td>{party}</td><td>{prank} / {len(peers)}</td>'+''.join(f'<td>{r["legislation"][k]}</td>' for k in keys)+f'<td><strong>{float(s):.2f}</strong></td></tr>')
 template=(ROOT/'candidates/legislative-comparison.html').read_text();head=template.split('<body>')[0];head=head.replace('2023–2024 legislative score comparison','2025–2026 Senate RIEP ranking');head=head.replace('Compare the RIEP three-stage legislative progress index with CEL State Legislative Effectiveness Scores for Rhode Island’s 2023–2024 session.','Full Senate ranking for the experimental 2025–2026 RIEP legislative progress index.');head=head.replace('</head>','<link rel="stylesheet" href="current-riep-ranking.css">\n</head>');header=template[template.index('<header'):template.index('<main')]
 page=head+'<body>'+header+'<main class="shell"><section class="card"><p class="eyebrow">Experimental RIEP calculation · 2025–2026</p><h1>Full Senate ranking</h1><p class="intro">All 38 Senate district records, ordered by the three-stage legislative progress index used on candidate profiles. A score of 1 represents the Senate comparison-set average.</p><p class="lawmaker-note">Provisional descriptive index · August 30, 2026 snapshot. This is an RIEP calculation, separate from the Center for Effective Lawmaking’s historical score.</p><div class="comparison-controls"><label for="ranking-search">Find a legislator<input type="search" id="ranking-search" placeholder="Search by name" /></label><button type="button" id="ranking-clear">Show all senators</button></div><p id="ranking-status" aria-live="polite">Showing all 38 Senate district records.</p><div class="table-scroll" tabindex="0" role="region" aria-label="Full Senate ranking"><table class="comparison-table"><caption>2025–2026 RIEP Senate index · Full-chamber and within-party ranks</caption><thead><tr><th scope="col">Senate rank</th><th scope="col">Senator</th><th scope="col">District</th><th scope="col">Party</th><th scope="col">Party rank</th><th scope="col">Lead-sponsored</th><th scope="col">Passed Senate</th><th scope="col">Became law</th><th scope="col">RIEP index</th></tr></thead><tbody>'+''.join(rows)+'</tbody></table></div><p class="source">Ranks use unrounded values; ties share a rank. Search filters the display without recalculating ranks. Select a linked senator to open the candidate profile.</p></section><section class="card"><h2>Calculation and coverage</h2><p><strong>38 ÷ 3 × (lead-sponsored ÷ Senate total + passed Senate ÷ Senate total + became law ÷ Senate total).</strong></p><p>Senate totals: '+f'{totals[0]:,} lead-sponsored bills; {totals[1]:,} bills passed by the Senate; {totals[2]:,} bills became law.'+'</p><p>Each stage receives equal weight. Cosponsorship and resolutions are excluded. Bills contribute at each stage they reach. This index does not include committee advancement, bill-significance weights, or CEL’s expected-performance benchmark. It is not an overall assessment of legislative service or policy quality.</p><p>Coverage is the project’s 38 current Senate district records, rather than every legislator who served during the term. Counts reflect the August 30, 2026 dataset and are not a live feed.</p><a class="score-comparison-link" href="legislative-comparison.html">Compare RIEP and CEL for 2023–2024 →</a><p class="source">Underlying research: <a href="https://status.rilegislature.gov/" target="_blank" rel="noopener">Rhode Island General Assembly Bill Status/History ↗</a></p></section></main><script src="current-riep-ranking.js"></script></body></html>'
 (ROOT/'candidates/current-riep-ranking.html').write_text(page)
if __name__=='__main__':build()
