"""Build the complete House ranking from the same snapshot used on profiles."""
import json,html
from fractions import Fraction
from house_legislative_index import dataset
import re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def build():
 data,by_district,party_by_district,_,_,_,_=dataset()
 records=list(by_district.values())
 incumbents={r['district_number']:r for r in json.loads((ROOT/'data/incumbent_records_2026.json').read_text())['records'] if r['chamber']=='house'}
 for r in records:
  slug=incumbents[r['district_number']]['candidate_id'].split('-primary-',1)[1] if r['district_number'] in incumbents and '-primary-' in incumbents[r['district_number']]['candidate_id'] else re.sub('[^a-z0-9]+','-',r['candidate_name'].lower()).strip('-')
  r['candidate_id']='house-'+str(r['district_number'])+'-primary-'+slug
 parties={r['candidate_id']:party_by_district[r['district_number']] for r in records}
 keys=['prime_sponsored','passed_chamber','became_law'];totals=[sum(r['legislation'][k] for r in records) for k in keys]
 score=lambda r:Fraction(75,3)*sum(Fraction(r['legislation'][k],t) for k,t in zip(keys,totals))
 assert sum(score(r) for r in records)==75
 rows=[]
 for r in sorted(records,key=lambda r:(-score(r),r['candidate_name'])):
  s=score(r);party=parties[r['candidate_id']];peers=[p for p in records if parties[p['candidate_id']]==party];rank=1+sum(score(p)>s for p in records);prank=1+sum(score(p)>s for p in peers)
  slug=r['candidate_id'].split('-primary-',1)[1];name=html.escape(r['candidate_name']);name=f'<a href="{slug}.html#riep-legislative-index">{name}</a>' if (ROOT/'candidates'/f'{slug}.html').exists() else name
  rows.append(f'<tr id="district-{r["district_number"]}" data-name="{html.escape(r["candidate_name"].lower(),quote=True)}"><td>{rank}</td><th scope="row">{name}</th><td>{r["district_number"]}</td><td>{party}</td><td>{prank} / {len(peers)}</td>'+''.join(f'<td>{r["legislation"][k]}</td>' for k in keys)+f'<td><strong>{float(s):.2f}</strong></td></tr>')
 template=(ROOT/'candidates/legislative-comparison.html').read_text();head=template.split('<body>')[0];head=head.replace('2023–2024 legislative score comparison','2025–2026 House RIEP ranking');head=head.replace('Compare the RIEP three-stage legislative progress index with CEL State Legislative Effectiveness Scores for Rhode Island’s 2023–2024 session.','Full House ranking for the experimental 2025–2026 RIEP legislative progress index.');head=head.replace('</head>','<link rel="stylesheet" href="current-riep-ranking.css">\n</head>');header=template[template.index('<header'):template.index('<main')]
 page=head+'<body>'+header+'<main class="shell"><section class="card"><p class="eyebrow">Experimental RIEP calculation · 2025–2026</p><h1>Full House ranking</h1><p class="intro">All 75 House district records, ordered by the three-stage legislative progress index used on candidate profiles. A score of 1 represents the House comparison-set average.</p><p class="lawmaker-note">Provisional descriptive index · September 22, 2026 snapshot. This is an RIEP calculation, separate from the Center for Effective Lawmaking’s historical score.</p><div class="comparison-controls"><label for="ranking-search">Find a legislator<input type="search" id="ranking-search" placeholder="Search by name" /></label><button type="button" id="ranking-clear">Show all representatives</button></div><p id="ranking-status" data-chamber="House" data-count="75" aria-live="polite">Showing all 75 House district records.</p><div class="table-scroll" tabindex="0" role="region" aria-label="Full House ranking"><table class="comparison-table"><caption>2025–2026 RIEP House index · Full-chamber and within-party ranks</caption><thead><tr><th scope="col">House rank</th><th scope="col">Representative</th><th scope="col">District</th><th scope="col">Party</th><th scope="col">Party rank</th><th scope="col">Lead-sponsored</th><th scope="col">Passed House</th><th scope="col">Became law</th><th scope="col">RIEP index</th></tr></thead><tbody>'+''.join(rows)+'</tbody></table></div><p class="source">Ranks use unrounded values; ties share a rank. Search filters the display without recalculating ranks. Select a linked representative to open the candidate profile.</p></section><section class="card"><h2>Calculation and coverage</h2><p><strong>75 ÷ 3 × (lead-sponsored ÷ House total + passed House ÷ House total + became law ÷ House total).</strong></p><p>House totals: '+f'{totals[0]:,} lead-sponsored bills; {totals[1]:,} bills passed by the House; {totals[2]:,} bills became law.'+'</p><p>Each stage receives equal weight. Cosponsorship and resolutions are excluded. Bills contribute at each stage they reach. This index does not include committee advancement, bill-significance weights, or CEL’s expected-performance benchmark. It is not an overall assessment of legislative service or policy quality.</p><p>Coverage is the project’s 75 House district records, including representatives who are not candidates in the 2026 election. Counts reflect the September 22, 2026 dataset and are not a live feed. Party labels use the 2025–2026 House roster.</p><a class="score-comparison-link" href="legislative-comparison.html">Compare RIEP and CEL for 2023–2024 →</a><p class="source">Underlying research: <a href="https://status.rilegislature.gov/" target="_blank" rel="noopener">Rhode Island General Assembly Bill Status/History ↗</a></p></section></main><script src="current-riep-ranking.js"></script></body></html>'
 (ROOT/'candidates/current-riep-house-ranking.html').write_text(page)
if __name__=='__main__':build()
