"""Build a searchable directory of published profile files from the ballot registry."""
import json,re,html
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
esc=lambda x:html.escape(str(x),quote=True)
def build():
 registry=json.loads(re.search(r'const candidateProfile = \((\{.*?\})\)\[candidate.candidate_id\]',(ROOT/'ballot.html').read_text())[1])
 roster=json.loads((ROOT/'data/whos_running_2026.json').read_text())['chambers']
 candidates={c['candidate_id']:dict(c,chamber=chamber,district_number=int(d)) for chamber,districts in roster.items() for d,race in districts.items() for c in race['candidates']}
 incumbent_ids={r['candidate_id'] for r in json.loads((ROOT/'data/incumbent_records_2026.json').read_text())['records']}
 cards=[];counts={'senate':0,'house':0};incumbents=0
 for id,slug in sorted(registry.items(),key=lambda x:(candidates[x[0]]['chamber']!='senate',candidates[x[0]]['district_number'],candidates[x[0]]['name'])):
  c=candidates[id];p=ROOT/'candidates'/f'{slug}.html';assert p.is_file(),p
  page=p.read_text();photo=re.search(r'<img[^>]+src="([^\"]+\.png)"[^>]*alt="[^\"]*'+re.escape(c['name'].split()[-1])+r'[^\"]*"',page,re.I)
  if not photo:photo=re.search(r'src="('+re.escape(slug)+r'\.png)"',page)
  assert photo,(slug,'portrait missing')
  image='candidates/'+photo[1] if not photo[1].startswith('/') else photo[1];assert (ROOT/image.lstrip('/')).is_file(),image
  counts[c['chamber']]+=1;incumbents+=c['chamber']=='senate' and id in incumbent_ids
  chamber=c['chamber'].title();party=c.get('party_label',c['party']);community=c.get('hometown','');status='Incumbent' if id in incumbent_ids else 'Candidate'
  search=' '.join([c['name'],community,chamber,str(c['district_number']),party]).lower()
  cards.append(f'<a class="profile-card" href="candidates/{slug}.html" data-search="{esc(search)}" data-chamber="{c["chamber"]}" data-party="{esc(c["party"])}"><img src="{esc(image)}" alt="" width="72" height="96" loading="lazy"><div><p class="district">{chamber} District {c["district_number"]}</p><h2>{esc(c["name"])}</h2><p class="community">{esc(community)}</p><p class="labels"><span class="party {c["party"].lower()}">{esc(party)}</span><span>{status}</span></p><span class="open-profile">View profile →</span></div></a>')
 template=(ROOT/'candidates/john-burke.html').read_text();header=template[template.index('<header'):template.index('<section class="hero"')] if '<section class="hero"' in template else ''
 # Keep the established RIEP masthead, without a candidate-specific hero.
 header=template[template.index('<header'):template.index('</header>')+9]
 header=re.sub(r'<nav.*?</nav>','<nav aria-label="Site navigation"><a href="index.html">Home</a><a href="running.html">Races &amp; candidates</a><a href="ballot.html">My ballot</a><a href="finance.html">Campaign finance</a></nav>',header,flags=re.S)
 output='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Candidate Profiles | Rhode Island Elections Project</title><meta name="description" content="Browse RIEP candidate profiles by name, district, chamber and party."><link rel="icon" href="/favicon.ico?v=20261001-logo" sizes="any"><link href="https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@400;500;600;700;800&family=Sora:wght@500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="candidates/john-burke.css?v=20261004-score-context"><link rel="stylesheet" href="candidate-profiles.css"><script defer src="candidate-profiles.js"></script></head><body>'''+header+f'''<main class="shell directory"><p class="eyebrow">RHODE ISLAND ELECTIONS PROJECT</p><h1>Candidate profiles</h1><p class="directory-intro">Explore campaign priorities, election results, campaign finance and public records in one place.</p><div class="coverage"><div><strong>{len(cards)}</strong><span>Available profiles</span></div><div><strong>{counts['senate']}</strong><span>Senate candidates</span></div><div><strong>{counts['house']}</strong><span>House candidates</span></div></div><p class="coverage-note">Profiles are available for all {incumbents} Senate incumbents, plus {counts["senate"]-incumbents} Senate challengers and {counts["house"]} House candidates. Profile pages are still under construction; available records vary by candidate.</p><form class="filters" role="search" onsubmit="return false"><div><label for="profile-search">Find a candidate or district</label><input id="profile-search" type="search" placeholder="Search name, town or district" aria-controls="profile-grid"></div><div><label for="profile-chamber">Chamber</label><select id="profile-chamber"><option value="">All chambers</option><option value="senate">Senate</option><option value="house">House</option></select></div><div><label for="profile-party">Party</label><select id="profile-party"><option value="">All parties</option><option value="DEM">Democratic</option><option value="REP">Republican</option></select></div><button type="reset">Clear filters</button></form><p id="profile-count" role="status" aria-live="polite">Showing all {len(cards)} profiles</p><div id="profile-grid" class="profile-grid">'''+''.join(cards)+'''</div><p id="profile-empty" hidden>No profiles match these filters. Try another name or clear the filters.</p></main><footer class="footer"><div class="shell">Rhode Island Elections Project · Independent, nonpartisan election information.</div></footer></body></html>'''
 (ROOT/'candidate-profiles.html').write_text(output+'\n');print(f'Directory: {len(cards)} profiles, {counts}')
if __name__=='__main__':build()
