const fs=require('fs'),assert=require('assert/strict'),cp=require('child_process'),vm=require('vm');
const model=require('../house-15-finance-model.js'),d=JSON.parse(fs.readFileSync('data/house_15_finance_model_2026.json'));
const current=JSON.parse(fs.readFileSync('data/candidate_finance_2026.json')),mirror=JSON.parse(fs.readFileSync('candidate_finance_2026.json'));
const old=JSON.parse(cp.execFileSync('git',['show','25970f11bee93cfd2c3f0a40eb45babf779b1048:data/candidate_finance_2026.json'],{maxBuffer:10000000}));
const slugs=d.candidates.map(c=>c.slug);
for(const p of current.profiles){if(!slugs.includes(p.slug))assert.deepEqual(p,old.profiles.find(o=>o.slug===p.slug));else assert.deepEqual(p,mirror.profiles.find(o=>o.slug===p.slug));}
assert.deepEqual(current.directory,old.directory);assert.deepEqual(current.donor_index.filter(x=>x.slug!==slugs[0]),old.donor_index.filter(x=>x.slug!==slugs[0]));
assert.equal(model.days('2026-07-01','2026-10-05'),97);assert.equal(model.days('2026-06-22','2026-10-05'),106);assert.equal(model.days(d.as_of,d.election_date)-1,29);
for(const c of d.candidates){const p=current.profiles.find(x=>x.slug===c.slug),s=model.stats(c);assert.equal(Math.round(s.receipts*100),Math.round(p.money_raised*100));assert.equal(Math.round(s.expenses*100),Math.round(p.money_spent*100));assert.equal(Math.round((p.beginning_cash+p.money_raised-p.money_spent)*100),Math.round(p.ending_cash*100));assert.equal(s.days,c.party==='REP'?97:106);const common=model.stats(c,d.common_start,d.common_end);assert.equal(common.days,97);assert.equal(common.receipts,s.receipts);assert.equal(common.expenses,s.expenses);assert.equal(model.scenario(c,0,0,29),c.cash);assert.equal(model.scenario(c,100,1000,29),c.cash-1900);assert(fs.existsSync('.'+c.source));}
const pap=current.profiles.find(x=>x.slug===slugs[0]),cr=current.profiles.find(x=>x.slug===slugs[1]);assert.equal(pap.in_kind_contributions,483);assert.equal(pap.receipt_transactions.length,79);assert.equal(pap.expenditure_transactions.length,67);assert.equal(pap.archived_reporting_periods.length,1);assert.equal(pap.archived_reporting_periods[0].ending_cash,28314.7);assert.equal(pap.filing_history.length,3);assert.equal(cr.filing_history.length,1);assert.equal(cr.original_documents.length,1);assert.equal(cr.receipt_transactions.length,8);assert.equal(cr.expenditure_transactions.length,13);
assert.equal(Math.round(model.stats(d.candidates[0]).burn*1000),1406);assert.equal(Math.round(model.stats(d.candidates[1]).burn*1000),863);assert(model.scenario(d.candidates[1],model.stats(d.candidates[1],d.common_start,d.common_end).daily,0,29)<0);
const empty={start:'2026-07-01',end:'2026-10-05',cash:0,receipt_transactions:[],expenditure_transactions:[]};assert.equal(model.stats(empty).burn,null);assert.equal(model.stats(empty).runway,null);assert.equal(d.missing_candidates[0].name,'Allan W Fung');
const html=fs.readFileSync('finance.html','utf8'),script=html.match(/<script>([\s\S]*)<\/script>/)[1].replace(/\n    boot\(\);/,'');const ctx={Intl,URLSearchParams,window:{location:{search:''}},document:{addEventListener(){}}};vm.createContext(ctx);vm.runInContext(script,ctx);
const choices=ctx.filingChoices(pap);assert.equal(choices.length,2);const archived=ctx.filingView(choices[1],pap);assert.equal(archived.ending_cash,28314.7);assert(!ctx.buildTransactions(archived).includes('27023'));const latest=ctx.filingView(choices[0],pap);assert.equal(latest.original_documents.length,1);assert.equal(latest.original_documents[0].href,pap.latest_filing_href);assert(ctx.buildHero(latest).includes('$20,511.54'));assert(ctx.buildHero(latest).includes('house-15-finance-model.html'));assert(ctx.buildTransactions(latest).includes('48HOURPRINT.COM'));
console.log('PASS: balances, schedules, common windows, scenarios, zero/missing data, archived Q2 rendering and unrelated-profile preservation');
(async()=>{
 const elements=new Map(),target={innerHTML:'',textContent:''};elements.set('model',target);
 const make=()=>({value:'',textContent:'',innerHTML:'',listeners:{},addEventListener(type,fn){this.listeners[type]=fn},checkValidity(){return Number.isFinite(Number(this.value))&&Number(this.value)>=0&&Number(this.value)<=1000000}});
 const document={getElementById(id){if(!elements.has(id)){const e=make();if(id.startsWith('daily-'))e.value=model.stats(d.candidates[Number(id.slice(6))],d.common_start,d.common_end).daily.toFixed(2);if(id.startsWith('receipts-'))e.value='0';elements.set(id,e);}return elements.get(id)}};
 const context={window:{document},document,Intl,Date,Number,fetch:async()=>({ok:true,json:async()=>d})};vm.createContext(context);vm.runInContext(fs.readFileSync('house-15-finance-model.js','utf8'),context);await new Promise(resolve=>setImmediate(resolve));
 assert(target.innerHTML.includes('Allan W Fung'));assert(target.innerHTML.includes('140.6%'));assert(!target.innerHTML.includes('NaN'));assert(!target.innerHTML.includes('Infinity'));assert(elements.get('output-1').innerHTML.includes('funding needed'));
 const input=elements.get('daily-1');input.value='0';input.listeners.input();assert(elements.get('output-1').innerHTML.includes('$1,646.65'));input.value='-1';input.listeners.input();assert(elements.get('output-1').textContent.includes('valid non-negative'));elements.get('reset-1').listeners.click();assert(elements.get('output-1').innerHTML.includes('funding needed'));
 console.log('PASS: rendered model, scenario input events, validation and reset');
})().catch(e=>{console.error(e.message);process.exitCode=1});
