const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),cp=require('child_process');
const read=p=>fs.readFileSync(p,'utf8'),load=n=>JSON.parse(read(`data/${n}.json`));
const entries=[['suzanna-l-alba','Suzanna L Alba',53,1062,null],['paul-m-santucci','Paul M Santucci',53,531,'santucci'],['william-w-o-brien',"William W O'Brien",54,1419,'obrien'],['arthur-j-corvese','Arthur J Corvese',55,1709,'corvese'],['joshua-j-giraldo','Joshua J Giraldo',56,449,'giraldo']];
const records=load('incumbent_records_2026').records,roster=load('whos_running_2026').chambers.house,primaries=load('candidate_profile_primary_returns_2026'),finances=load('candidate_finance_2026').profiles;
const index=read('index.html'),ctx={normalizeSearchText:s=>s.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()};vm.createContext(ctx);let start=index.indexOf('    function buildCandidateProfileHref('),end=index.indexOf('\n    function ',start+5);vm.runInContext(index.slice(start,end),ctx);
const voting=JSON.parse(read('candidates/house-voting-patterns/positions.json')).positions;
for(const [slug,name,d,votes,surname] of entries){
 const p=read(`candidates/${slug}.html`),encoded=name.replace(/'/g,'&#x27;');assert(p.includes(`<h1>${encoded}</h1>`)||p.includes(`<h1>${name}</h1>`));assert(p.includes(votes.toLocaleString('en-US')+' votes'));assert(p.includes('Official results'));assert(p.includes('100%'));assert(p.includes('October 7, 2026'));
 assert(p.includes(`/running.html?chamber=house&amp;district=${d}&amp;election=general`));assert(p.includes(`/finance.html?slug=${slug}`));assert(!p.includes('Senate District'));assert(!p.includes('Eleven Senate votes'));assert(!p.includes('bffi-scorecard'));
 assert.equal(p.includes('data-voting-widget'),!!surname);assert.equal(p.includes('riep-legislative-index'),!!surname);
 if(surname){assert(p.includes(`mailto:rep-${surname}@rilegislature.gov`));assert(p.includes(`data-candidate="${encoded}"`)||p.includes(`data-candidate="${name}"`));assert(p.includes(`current-riep-house-ranking.html#district-${d}`));assert(p.includes('of 75 House district records'));assert(voting.some(x=>x.name===name));const rec=records.find(r=>r.chamber==='house'&&r.district_number===d);for(const b of rec.legislation_detail.lead_sponsored)assert(p.includes(b.bill));assert(p.includes('Session attendance'));}
 else{assert(p.includes('General Assembly record not applicable'));assert(!p.includes('rep-desimone'));assert(!p.includes('class="lawmaker-score"'));}
 assert.equal(ctx.buildCandidateProfileHref({name,chamber:'house',district_number:d}),`candidates/${slug}.html`);
 for(const route of ['ballot.html','running.html','race-page.js','candidate-profiles.html'])assert(read(route).includes(slug));assert(read(`races/house-${d}.html`).includes('20261007-house53-56'));
 const ids=[...p.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);for(const m of p.matchAll(/href="#([^"]+)"/g))assert(ids.includes(m[1]));
 for(const m of p.matchAll(/<img[^>]+src="([^"/]+\.(?:png|jpg|webp))"/g))assert(fs.existsSync('candidates/'+m[1]));
 assert.equal(primaries[slug].votes,votes);assert(primaries[slug].source_url.includes('/ballot-items/'));assert(roster[d].candidates.find(c=>c.name===name).profile_available);
 const f=finances.find(f=>f.slug===slug);for(const k of ['money_raised','money_spent','ending_cash'])assert(p.includes('$'+f[k].toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})));assert(p.includes(slug==='joshua-j-giraldo'?'6/30/2026':'July 1, 2026 to October 5, 2026'));
}
const alba=read('candidates/suzanna-l-alba.html');assert(alba.includes('src="suzanna-l-alba.webp"'));assert(read('candidate-profiles.html').includes('src="candidates/suzanna-l-alba.webp"'));assert(read('candidate-profiles.html').includes('suzanna l alba suzy alba'));assert(alba.includes('Smithfield Town Council from 2012–2022'));assert(alba.includes('https://www.suzyalba.com/priorities/'));assert(alba.includes('Jobs and workforce development'));assert(alba.includes('Open space and preservation'));assert(alba.includes('mailto:SuzyAlbaforSmithfield@gmail.com'));
const paul=read('candidates/paul-m-santucci.html');assert(paul.includes('Republican · Incumbent'));assert(paul.includes('First elected to the House in November 2024'));assert(paul.includes('CEL score does not apply'));assert(!paul.includes('Historical score covering the 2023–2024 legislative session'));assert(!paul.includes('Brian J Rea'));
const corvese=read('candidates/arthur-j-corvese.html');assert(corvese.includes('Campaign website: stated record'));assert(corvese.includes('earlier legislative work'));assert(corvese.includes('Chair'));assert(corvese.includes('House Labor Committee'));
for(const f of ['data/independent_finance_supplement_2026.json'])assert.equal(read(f),cp.execFileSync('git',['show',`5fbc9d8:${f}`],{maxBuffer:12e6,encoding:'utf8'}));
console.log('PASS: five D53–56 profiles, competitive pair, official primaries, source portraits, campaign research, incumbent scores, current routes and current finance periods');
