const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),slug='colleen-m-crudele';
const data=JSON.parse(fs.readFileSync('data/candidate_finance_2026.json')),p=data.profiles.find(p=>p.slug===slug);
assert.deepEqual(p,JSON.parse(fs.readFileSync('candidate_finance_2026.json')).profiles.find(p=>p.slug===slug));
assert.equal(p.finance_status,'available');assert.equal(p.reporting_period_label,'June 22, 2026 to October 5, 2026');
assert.equal(p.money_raised,11991.79);assert.equal(p.money_spent,10345.14);assert.equal(p.ending_cash,1646.65);
assert.equal(Math.round((p.beginning_cash+p.money_raised-p.money_spent)*100),164665);
assert.equal(Math.round(p.top_donors.reduce((s,d)=>s+d.amount,0)*100),1199179);
assert.equal(Math.round(p.spending_categories.reduce((s,d)=>s+d.amount,0)*100),1034514);
assert(p.top_donors[0].notes.includes('zero loan proceeds'));assert.equal(p.filing_history.length,1);assert(!p.filing_history.some(h=>/^Q[12]/.test(h.label)));
for(const donor of p.top_donors)assert(data.donor_index.some(d=>d.slug===slug&&d.donor===donor.donor&&d.amount===donor.amount));
assert(fs.existsSync('.'+p.original_documents[0].href));
const html=fs.readFileSync('finance.html','utf8'),script=html.match(/<script>([\s\S]*)<\/script>/)[1].replace(/\n    boot\(\);/,'');
const ctx={Intl,URLSearchParams,window:{location:{search:'?slug='+slug}},document:{addEventListener(){}}};vm.createContext(ctx);vm.runInContext(script,ctx);
assert.equal(ctx.getRequestedProfile(data.profiles).slug,slug);
const rendered=ctx.buildHero(p)+ctx.buildMoneyFlow(p)+ctx.buildHistory(p)+ctx.buildVerification(p)+ctx.buildDonorHighlights(p);
for(const amount of ['$11,991.79','$10,345.14','$1,646.65'])assert(rendered.includes(amount));
assert(rendered.includes('Filing-period snapshot'));assert(rendered.includes('Filing history'));assert(!rendered.includes('Quarter snapshot'));assert(rendered.includes(p.original_documents[0].href));
const page=fs.readFileSync('candidates/'+slug+'.html','utf8');for(const amount of ['$11,991.79','$10,345.14','$1,646.65'])assert(page.includes(amount));
assert(page.includes(p.reporting_period_label));assert(page.includes('work across party lines'));
console.log('PASS: Crudele filing balances, schedules, donor index, source PDF, finance rendering and profile snapshot');
