const fs=require('fs'),assert=require('assert'),cp=require('child_process'),vm=require('vm');
const rows=[['veronicka-vega',49,'DEM',5074.45,1878,3965.13,2987.32,0,323.65,18,12],['jon-d-brien',49,'IND',25097.59,6450,15082.02,16465.57,22689.98,0,12,12],['stephen-casey',50,'DEM',23644.71,750,14680.83,9713.88,0,0,5,71],['robert-d-phillips',51,'DEM',15327.32,7725,4053.09,18999.23,5617.53,0,10,21],['alex-d-marszalkowski',52,'DEM',17680.80,0,1350,16330.80,1819.08,0,0,3]];
const data=JSON.parse(fs.readFileSync('data/candidate_finance_2026.json'));const mirror=JSON.parse(fs.readFileSync('candidate_finance_2026.json'));const baseline=JSON.parse(cp.execFileSync('git',['show','914f6401f1e849e048a8346e6cac2b49bf56cd49:data/candidate_finance_2026.json'],{maxBuffer:12e6}));const targets=new Set(rows.map(x=>x[0]));const cents=x=>Math.round(x*100),sum=a=>a.reduce((n,x)=>n+cents(x.amount),0);const registryFile=fs.readFileSync('ballot.html','utf8'),registry=JSON.parse(registryFile.match(/const candidateProfile = \((\{.*?\})\)\[candidate.candidate_id\]/)[1]);
for(const [slug,district,party,begin,raised,spent,end,liabilities,inkind,receiptCount,expenseCount] of rows){
 const p=data.profiles.find(x=>x.slug===slug),page=fs.readFileSync(`candidates/${slug}.html`,'utf8');assert(p);assert.deepStrictEqual(p,mirror.profiles.find(x=>x.slug===slug));
 for(const [k,v] of Object.entries({beginning_cash:begin,money_raised:raised,money_spent:spent,ending_cash:end,total_liabilities:liabilities,in_kind_contributions:inkind}))assert.equal(cents(p[k]),cents(v),`${slug} ${k}`);
 assert.equal(cents(begin+raised-spent),cents(end));assert.equal(sum(p.receipt_transactions),cents(raised));assert.equal(sum(p.in_kind_transactions),cents(inkind));assert.equal(sum(p.expenditure_transactions),cents(spent));assert.equal(sum(p.source_buckets),cents(raised));assert.equal(sum(p.spending_categories),cents(spent));assert.equal(p.receipt_transactions.length+p.in_kind_transactions.length,receiptCount);assert.equal(p.expenditure_transactions.length,expenseCount);
 assert(page.includes(`District ${district}`));assert(page.includes(`/running.html?chamber=house&amp;district=${district}&amp;election=general`));assert(page.includes(`/finance.html?slug=${slug}`));assert(page.includes(`src="${p.latest_filing_href}"`));assert(page.includes('Read the financial report on this page'));assert(page.includes('October 7, 2026'));
 const pdf=fs.readFileSync(p.latest_filing_href.slice(1));assert(pdf.subarray(0,5).equals(Buffer.from('%PDF-')));assert(p.original_documents.some(d=>d.href===p.latest_filing_href&&d.embed));assert(Object.values(registry).includes(slug));assert(fs.readFileSync('candidate-profiles.html','utf8').includes(`candidates/${slug}.html`));assert(fs.readFileSync('race-page.js','utf8').includes(`"${slug}"`));assert(fs.readFileSync(`races/house-${district}.html`,'utf8').includes('20261007-house49-52'));
 if(slug==='veronicka-vega'){assert(!page.includes('id="voting-patterns"'));assert(!page.includes('id="riep-legislative-index"'));assert(page.includes('not applicable'));}else{assert(page.includes('id="voting-patterns"'));assert(page.includes('id="riep-legislative-index"'));assert(page.includes('Center for Effective Lawmaking'));assert(page.includes('Session attendance'));}
 const old=baseline.profiles.find(x=>x.slug===slug);if(old){assert(p.archived_reporting_periods.some(x=>JSON.stringify(x)===JSON.stringify(Object.fromEntries(Object.entries(old).filter(([k])=>!['archived_reporting_periods','filing_history'].includes(k))))));assert.deepStrictEqual(p.filing_history.slice(0,old.filing_history.length),old.filing_history);}
}
for(const old of baseline.profiles.filter(p=>!targets.has(p.slug)))assert.deepStrictEqual(data.profiles.find(x=>x.slug===old.slug),old,old.slug);
assert.deepStrictEqual(data.donor_index.filter(x=>!targets.has(x.slug)),baseline.donor_index.filter(x=>!targets.has(x.slug)));
const brien=fs.readFileSync('candidates/jon-d-brien.html','utf8');assert(brien.includes('Independent · Incumbent'));assert(brien.includes('a 2026 party-primary vote total is not assigned'));assert(!brien.includes('#61 of 66 House Democrats'));
const phillips=data.profiles.find(x=>x.slug==='robert-d-phillips');assert.equal(phillips.accounts_payable,-82.47);assert(phillips.finance_snapshot_note.includes('$50.00'));assert.equal(phillips.archived_reporting_periods.at(-1).ending_cash,15377.32);
const finance=fs.readFileSync('finance.html','utf8');const script=[...finance.matchAll(/<script(?: [^>]*)?>([\s\S]*?)<\/script>/g)].map(x=>x[1]).find(x=>x.includes('function buildVerification'));new vm.Script(script);const start=script.indexOf('    function buildVerification('),stop=script.indexOf('    function getNamedDonorIndex',start);const context={escapeHtml:x=>String(x)};vm.createContext(context);vm.runInContext(script.slice(start,stop),context);const rendered=context.buildVerification(data.profiles.find(x=>x.slug==='stephen-casey'));assert(rendered.includes('<iframe'));assert(rendered.includes('stephen-casey-2026-10-05-28-day.pdf'));
console.log('PASS: five D49–52 profiles, period totals and transactions, source PDF viewers, routes, score eligibility, historical preservation and unrelated finance data');
