const fs=require('fs'),assert=require('assert/strict'),cp=require('child_process'),vm=require('vm'),crypto=require('crypto');
const read=p=>fs.readFileSync(p,'utf8'),load=p=>JSON.parse(read(p));
const main=load('data/candidate_finance_2026.json'),mirror=load('candidate_finance_2026.json');
const old=JSON.parse(cp.execFileSync('git',['show','38af306:data/candidate_finance_2026.json'],{encoding:'utf8',maxBuffer:12e6}));
const entries=[['jennifer-smith-boylan',66,711,1450.35,32548,10,11,2202],['nicole-p-jellinek',67,1247,3094.84,25013.95,12,13,1706],['june-s-speakman',68,2000,2877.04,11920.51,14,8,1795],['susan-ann-donovan',69,910,1815.95,15318.17,6,15,1208],['john-g-edwards',70,-191.12,4036.30,71354.83,6,13,1105]];
const slugs=entries.map(x=>x[0]),cents=n=>Math.round(n*100),sum=rs=>cents(rs.reduce((n,r)=>n+r.amount,0));
const sourceHashes={"jennifer-smith-boylan": "730c7c83d54aa085e6b8f7dc79a70efff25675f7edfd1c86edd355ceb2a45902", "nicole-p-jellinek": "4ac096d29d4df0ab351a39466c12db475f0d1e517929f22c1e0ac9f988327517", "june-s-speakman": "187c3d070ab6cd93d6663caf9e46cd354f6d51a20ac6fb5900d5389ffbeb14da", "susan-ann-donovan": "73d3aff084a1164db410a980e040b3aba7522eb306db2f6fc19ae49139729c38", "john-g-edwards": "6feac866f0ec4b2e904dcb3eeaa1bb2328b005451cbc85f83164de2e6fd05553"};
for(const [slug,d,raised,spent,end,nr,ne,votes] of entries){
 const p=main.profiles.find(p=>p.slug===slug),prior=old.profiles.find(p=>p.slug===slug),page=read(`candidates/${slug}.html`);
 assert.deepEqual(p,mirror.profiles.find(p=>p.slug===slug));assert.deepEqual([p.money_raised,p.money_spent,p.ending_cash],[raised,spent,end]);
 assert.equal(sum(p.receipt_transactions),cents(raised));assert.equal(sum(p.expenditure_transactions),cents(spent));assert.equal(sum(p.source_buckets),cents(raised));assert.equal(sum(p.spending_categories),cents(spent));assert.equal(cents(p.beginning_cash+raised-spent),cents(end));assert.equal(cents(end-p.total_liabilities),cents(p.total_fund_balance));
 assert.equal(p.receipt_transactions.length,nr);assert.equal(p.expenditure_transactions.length,ne);assert.equal(p.reporting_period_start,d===67?'2026-09-02':'2026-07-01');
 const snapshot={...prior};delete snapshot.filing_history;delete snapshot.archived_reporting_periods;assert.deepEqual(p.archived_reporting_periods.at(-1),snapshot);assert.deepEqual(p.filing_history.slice(0,-1),prior.filing_history);
 assert.equal(crypto.createHash('sha256').update(fs.readFileSync(p.latest_filing_href.slice(1))).digest('hex'),sourceHashes[slug]);
 for(const text of [p.reporting_period_label,p.latest_filing_href,'<iframe','Official results',votes.toLocaleString('en-US')+' votes'])assert(page.includes(text),slug+' '+text);
 assert(!page.includes('Senate District'));assert(page.includes(`/running.html?chamber=house&amp;district=${d}&amp;election=general`));
 if(d===67){assert(!page.includes('riep-legislative-index'));assert(!page.includes('data-voting-widget'));assert(page.includes('General Assembly record not applicable'));assert(page.includes('77.44%'));assert(page.includes('https://www.nicolejellinek.com/contact-1'));assert(!page.includes('rep-desimone'));}
 else {assert(page.includes('of 75 House district records'));assert(page.includes('data-voting-widget'));assert(page.includes('Session attendance'));}
 for(const route of ['index.html','ballot.html','running.html','race-page.js','candidate-profiles.html'])assert(read(route).includes(slug));assert(read(`races/house-${d}.html`).includes('house66-70'));
 const ids=[...page.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);for(const m of page.matchAll(/href="#([^"]+)"/g))assert(ids.includes(m[1]));assert(fs.statSync(`candidates/${slug}.jpg`).size>10000);
}
for(const p of main.profiles)if(![...slugs,'terri-denise-cortvriend','marvin-abney','alex-finkelman','lauren-h-carson'].includes(p.slug))assert.deepEqual(p,old.profiles.find(x=>x.slug===p.slug),p.slug);
assert.deepEqual(main.donor_index.filter(p=>![...slugs,'terri-denise-cortvriend','marvin-abney','alex-finkelman','lauren-h-carson'].includes(p.slug)),old.donor_index.filter(p=>![...slugs,'terri-denise-cortvriend','marvin-abney','alex-finkelman','lauren-h-carson'].includes(p.slug)));
const edwards=main.profiles.find(p=>p.slug==='john-g-edwards');assert.equal(edwards.receipts_label,'Net cash receipts');assert.equal(edwards.returned_checks,-500);assert.equal(edwards.interest_received,8.88);assert.equal(edwards.accounts_payable_repayments,375);assert.equal(edwards.receipt_transactions.find(r=>r.type==='NSF Check').donor,'RI STATE ASSOCIATION OF FIREFIGHTERS');assert(edwards.top_donors.every(r=>r.amount>0));assert.equal(edwards.top_donors.length,2);assert.equal(sum(main.profiles.find(p=>p.slug==='jennifer-smith-boylan').in_kind_transactions),29855);
assert.equal(main.profiles.find(p=>p.slug==='susan-ann-donovan').refunds_rebates,100);
const independent=load('data/whos_running_2026.json').chambers.house['67'].candidates.find(c=>c.party==='IND');assert(independent);assert(!independent.profile_available);assert(!fs.existsSync('candidates/joseph-a-depasquale.html'));assert(!read('candidate-profiles.html').includes('candidates/joseph-a-depasquale.html'));
const html=read('finance.html');let script=[...html.matchAll(/<script\b[^>]*>(.*?)<\/script>/gs)].map(m=>m[1]).join('\n').replace('    boot();','');
const nodes={financeApp:{innerHTML:''},financeFilingSelect:{addEventListener(e,cb){this[e]=cb;}}},ctx={URL,URLSearchParams,console,Intl,window:{location:{search:'',href:'https://example.org/finance.html'},history:{replaceState(a,b,url){ctx.window.location.href=String(url);ctx.window.location.search=url.search;}}},document:{addEventListener(){},getElementById:id=>nodes[id]}};
vm.createContext(ctx);vm.runInContext(script,ctx);let checked=0;
for(const p of main.profiles)for(const c of ctx.filingChoices(p)){ctx.renderProfile(p,main,c.key);assert(!nodes.financeApp.innerHTML.includes('NaN'));assert.equal((nodes.financeApp.innerHTML.match(/id="financeFilingSelect"/g)||[]).length,1);assert(nodes.financeApp.innerHTML.indexOf('id="financeFilingSelect"')>nodes.financeApp.innerHTML.indexOf('<aside class="panel hero-side'));checked++;}
ctx.renderProfile(edwards,main,'latest');assert(nodes.financeApp.innerHTML.includes('-$191.12'));assert(nodes.financeApp.innerHTML.includes('negative receipts'));const q2=ctx.filingChoices(edwards).find(c=>c.label==='Q2 2026');nodes.financeFilingSelect.change({target:{value:q2.key}});assert.equal(new URL(ctx.window.location.href).searchParams.get('period'),q2.key);assert(!nodes.financeApp.innerHTML.includes(edwards.latest_filing_href));assert(nodes.financeApp.innerHTML.includes('Q2 2026'));assert(!ctx.filingView(q2,edwards).returned_checks);
console.log('PASS: five D66–70 profiles, finance reconciliation/history, source documents, Independent exclusion and '+checked+' filing renders with integrated selector');
